In [191]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

df_Accidents_ML  = pd.read_csv('data/Accidents0515.csv')
y = df_Accidents_ML.Accident_Severity

%matplotlib inline

In [192]:
# ['Accident_Index', 'Location_Easting_OSGR', 'Location_Northing_OSGR',
#        'Longitude', 'Latitude', 'Police_Force', 'Accident_Severity',
#        'Number_of_Vehicles', 'Number_of_Casualties', 'Date', 'Day_of_Week',
#        'Time', 'Local_Authority_(District)', 'Local_Authority_(Highway)',
#        '1st_Road_Class', '1st_Road_Number', 'Road_Type', 'Speed_limit',
#        'Junction_Detail', 'Junction_Control', '2nd_Road_Class',
#        '2nd_Road_Number', 'Pedestrian_Crossing-Human_Control',
#        'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions',
#        'Weather_Conditions', 'Road_Surface_Conditions',
#        'Special_Conditions_at_Site', 'Carriageway_Hazards',
#        'Urban_or_Rural_Area', 'Did_Police_Officer_Attend_Scene_of_Accident',
#        'LSOA_of_Accident_Location']
X = df_Accidents_ML[['Day_of_Week',
       'Road_Type', 'Speed_limit',
       'Junction_Detail', 'Light_Conditions',
       'Weather_Conditions', 'Road_Surface_Conditions','Carriageway_Hazards']]
X

,Day_of_Week,Road_Type,Speed_limit,Junction_Detail,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Carriageway_Hazards
0,3,6,30,0,1,2,2,0
1,4,3,30,6,4,1,1,0
2,5,6,30,0,4,1,1,0
3,6,6,30,0,1,1,1,0
4,2,6,30,0,7,1,2,0
5,3,6,30,0,1,2,2,0
6,5,6,30,3,4,1,1,0
7,6,3,30,0,1,1,1,0
8,7,6,30,6,4,1,1,0
9,7,6,30,3,1,1,1,0
10,1,6,30,6,4,1,1,0
11,3,6,30,6,4,1,2,0
12,3,2,30,3,1,2,2,0
13,3,2,30,3,4,2,2,0
14,3,3,30,0,1,1,1,0
15,3,6,30,3,1,1,1,0
16,5,6,30,3,4,1,1,0
17,6,6,30,3,1,1,1,0
18,6,6,30,0,4,1,1,0
19,7,6,30,3,4,1,1,0
20,2,6,30,0,4,1,1,0
21,2,6,30,3,4,1,1,0
22,2,3,30,6,4,1,4,0
23,3,6,30,6,4,1,1,0
24,7,3,30,3,1,1,2,0
25,4,6,30,3,4,2,2,0
26,1,6,30,0,4,1,1,0
27,7,6,30,6,1,2,2,0
28,3,3,30,6,4,2,2,0
29,4,6,30,3,4,1,1,0
...,...,...,...,...,...,...,...,...
1780623,2,6,60,3,1,1,1,0
1780624,6,6,60,0,1,1,1,0
1780625,2,3,70,0,6,2,5,0
1780626,2,6,30,0,1,1,1,0
1780627,1,6,30,3,1,1,1,0
1780628,5,6,60,0,1,2,2,0
1780629,1,3,70,0,1,1,1,0
1780630,6,3,70,0,1,1,1,0
1780631,4,3,70,0,6,1,1,0
1780632,5,6,60,3,1,1,1,0
1780633,1,6,60,0,1,1,1,0
1780634,7,6,60,0,1,1,1,0
1780635,1,6,60,0,6,1,1,0
1780636,3,1,30,1,1,1,1,0
1780637,6,6,60,0,1,1,1,0
1780638,2,3,70,0,1,1,1,0
1780639,4,6,30,6,4,1,2,0
1780640,4,6,60,0,6,1,2,0
1780641,2,6,60,0,1,2,2,0
1780642,4,6,60,0,6,1,1,7
1780643,6,6,60,3,6,2,2,0
1780644,3,6,30,3,4,1,2,0
1780645,3,6,60,0,6,4,2,0
1780646,4,6,30,0,4,2,2,0
1780647,1,6,60,0,6,7,4,0
1780648,6,6,60,0,1,1,2,0
1780649,4,6,60,3,1,1,2,0
1780650,4,3,70,0,6,4,2,0
1780651,7,6,60,5,1,2,2,0
1780652,5,3,70,0,6,3,4,0

In [193]:
X_train, X_test, y_train, y_test = train_test_split(X,y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(1335489, 8) (445164, 8) (1335489,) (445164,)

In [194]:
clf_1 = DecisionTreeClassifier().fit(X_train, y_train)
clf_2 = DecisionTreeClassifier().fit(X_test, y_test)
z1 = clf_1.predict(X_train)
z2 = clf_2.predict(X_test)
print(len(X_train), len(y_train), len(z1))
print(len(X_test), len(y_test), len(z2))

1335489 1335489 1335489
445164 445164 445164

In [195]:
X_train['target_actual'] = y_train
X_train['target_expected'] = z1
X_train

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

,Day_of_Week,Road_Type,Speed_limit,Junction_Detail,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Carriageway_Hazards,target_actual,target_expected
1742690,1,6,30,0,1,1,1,0,2,3
1588643,4,6,60,0,1,8,2,0,2,3
1701362,7,6,30,0,4,4,1,0,3,3
989495,5,3,70,0,1,8,1,0,3,3
329829,6,6,30,3,4,1,1,0,3,3
558154,6,6,30,9,1,1,1,0,3,3
1134023,2,6,30,8,1,1,1,0,3,3
588756,2,6,30,3,4,2,2,0,3,3
881257,3,1,30,1,1,1,1,0,3,3
461004,7,3,40,0,4,1,1,0,3,3
1679668,5,7,30,1,1,1,1,0,3,3
945680,4,1,30,1,1,2,2,0,3,3
14679,3,6,30,0,1,1,1,0,3,3
1171559,1,6,40,3,1,1,1,0,3,3
1344785,2,6,60,0,1,5,2,0,3,3
767808,5,2,30,3,1,1,1,0,3,3
580743,4,6,30,3,4,1,1,0,3,3
179964,3,6,30,0,1,1,1,0,3,3
1741776,3,6,30,6,4,9,1,0,3,3
1171504,1,6,30,0,1,1,1,0,3,3
1177417,3,6,30,0,4,1,1,0,3,3
206853,1,6,30,6,4,1,1,0,3,3
1179040,7,6,30,3,1,1,1,0,3,3
1242945,6,3,30,6,4,8,2,0,3,3
506828,5,6,30,0,1,1,1,0,3,3
1437959,5,3,70,0,1,5,2,0,3,3
1010504,6,6,30,0,1,2,2,0,3,3
904562,6,6,30,0,1,1,1,0,3,3
944486,5,6,30,3,1,1,1,0,3,3
1543623,2,6,30,0,1,1,1,0,3,3
...,...,...,...,...,...,...,...,...,...,...
1412526,3,6,30,3,1,1,1,0,3,3
1559845,6,6,60,0,6,1,1,0,3,3
1562625,7,6,30,7,1,1,1,0,3,3
1043617,6,6,30,3,4,2,2,0,3,3
439355,5,6,40,3,4,1,1,0,3,3
539755,6,6,40,8,1,1,2,0,3,3
1492513,3,6,30,0,1,1,1,0,2,3
345502,1,6,30,3,1,2,2,0,3,3
437296,4,6,60,0,1,1,2,0,3,3
736520,3,6,30,0,1,1,1,0,3,3
27938,5,6,30,0,1,1,1,0,2,3
1155344,3,3,30,2,1,1,1,0,3,3
222550,6,6,30,0,1,1,1,0,3,3
15127,4,6,30,3,1,1,1,0,3,3
7983,5,3,30,0,1,1,1,0,3,3
146467,6,6,30,0,4,1,1,0,3,3
160335,2,6,30,0,1,1,1,0,3,3
1116190,3,6,30,3,1,1,1,0,3,3
886517,5,6,30,3,4,2,2,0,3,3
1128745,1,6,60,0,1,1,1,0,3,3
303437,2,6,60,0,6,1,1,0,3,3
358849,2,6,30,0,1,1,1,0,3,3
248191,7,3,60,9,1,3,2,0,3,3
1547643,6,6,40,1,1,1,1,0,3,3
43589,7,6,30,9,4,2,2,0,3,3
1396398,1,6,60,3,1,1,1,0,2,3
535992,6,3,40,9,1,1,2,0,3,3
676018,2,6,30,3,4,1,1,0,3,3
539639,6,3,50,0,1,1,1,0,3,3
1710885,5,2,30,0,1,1,1,0,3,3

In [196]:
X_test['target_actual'] = y_test
X_test['target_expected'] = z2
X_test

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

,Day_of_Week,Road_Type,Speed_limit,Junction_Detail,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Carriageway_Hazards,target_actual,target_expected
1415041,6,6,30,3,1,1,1,0,3,3
1632563,5,6,60,0,1,1,1,0,2,3
758217,4,6,30,6,1,1,1,0,3,3
164423,5,3,70,0,1,1,1,0,3,3
981494,3,6,60,0,1,2,2,0,3,3
1663377,2,6,30,0,1,1,1,0,3,3
1586790,7,1,50,5,1,1,1,0,3,3
1604793,7,1,30,1,1,1,4,0,3,3
1234036,6,1,30,2,1,2,2,0,3,3
392036,2,6,30,0,4,1,1,0,3,3
1607804,4,3,70,3,1,1,1,0,2,3
845791,7,6,30,0,1,1,1,0,3,3
246390,5,6,60,0,1,1,1,0,3,3
959204,4,3,40,0,1,1,1,0,3,3
710702,7,6,40,0,1,1,1,0,3,3
1059603,5,6,30,0,1,2,2,0,3,3
1775924,5,3,30,3,1,1,2,0,3,3
1035175,7,6,30,3,1,1,1,0,3,3
90878,3,6,60,0,1,1,1,0,2,3
1316885,1,3,70,0,6,1,1,0,3,3
1288546,3,6,60,0,1,1,1,0,2,3
1650928,1,6,30,3,4,1,1,0,2,3
1078699,3,6,30,3,4,1,1,0,3,3
1602613,1,6,30,9,1,1,1,0,3,3
554310,4,9,30,0,1,1,1,0,3,3
1053630,6,6,60,3,1,1,1,0,2,3
1384668,4,6,30,0,1,1,1,0,3,3
417591,6,6,30,0,4,1,2,0,2,3
351431,4,6,60,0,1,1,2,0,3,3
1147376,6,6,30,0,4,2,2,0,3,3
...,...,...,...,...,...,...,...,...,...,...
1686537,2,3,70,0,1,1,1,0,3,3
581859,3,6,30,3,1,1,1,0,3,3
730481,6,6,60,3,1,1,2,0,3,3
512607,5,6,60,0,1,1,1,0,3,3
124081,3,3,70,5,4,1,2,0,3,3
745084,5,6,30,0,4,1,1,0,3,3
1692927,4,6,30,6,1,1,1,0,3,3
196015,4,6,30,3,1,2,2,0,3,3
179922,4,7,70,0,1,1,1,0,3,3
1339026,4,6,30,0,1,1,1,0,2,3
292177,6,3,70,5,1,1,1,0,3,3
748747,6,6,30,0,4,1,2,0,3,3
1259605,1,1,40,1,1,1,1,0,3,3
1519306,2,6,30,0,4,1,1,0,3,3
141414,7,6,30,0,1,1,1,0,3,3
981297,2,6,60,8,1,1,1,0,3,3
583201,3,6,30,3,1,1,1,0,3,3
1562267,3,6,40,3,1,1,1,0,2,3
568329,2,6,60,0,6,8,4,0,3,3
201879,6,6,30,6,1,1,1,0,3,3
765511,2,3,50,6,1,1,1,2,3,3
1013024,2,6,40,0,1,1,1,0,3,3
1029906,3,6,30,0,1,1,1,0,3,3
45533,6,6,30,0,4,1,2,0,3,3
1646465,6,3,50,0,4,1,1,0,3,3
1091704,2,3,30,0,1,1,2,0,3,3
37532,1,6,30,6,4,1,1,0,2,3
851244,6,6,30,0,1,2,2,0,3,3
1366004,4,1,30,1,1,1,1,0,3,3
285223,1,6,30,3,1,2,2,0,3,3

In [ ]:
# z1 = np.reshape(z1, (-1, len(z1)))
# z2 = np.reshape(z2, (-1, len(z2)))

# p_train = plt.contourf(X_train.Road_Type, y_train[:len(z1)], z1, cmap=plt.cm.Paired)
# p_test = plt.contourf(X_test.Road_Type, y_test[:len(z2)], z2, cmap=plt.cm.Paired)
# plt.axis("tight")
# plt.show()